'use client'

import { useEffect,useState } from 'react'
import { useParams } from 'next/navigation'
import Link from 'next/link'
import { PageSkeleton } from '@/components/ui/Skeleton'
import { NetworkBadge } from '@/components/NetworkBadge'
import { EventTable } from '@/app/dashboard/activity/page'
import { Icon } from '@/components/ui/Icon'

export default function WalletSupportPage(){const{id,walletId}=useParams<{id:string;walletId:string}>();const[data,setData]=useState<any>();const[loading,setLoading]=useState(true);const[revealed,setRevealed]=useState<string>();const[error,setError]=useState('');useEffect(()=>{fetch(`/api/apps/${id}/wallets/${walletId}/support`).then(r=>r.json()).then(setData).finally(()=>setLoading(false))},[id,walletId]);if(loading)return <PageSkeleton/>;if(!data?.wallet)return <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-5 text-red-800">Wallet could not be loaded.</div>;const w=data.wallet,devices=w.wallet_devices??[],pending=(data.device_requests??[]).filter((r:any)=>r.status==='pending'&&new Date(r.expires_at)>new Date());const reveal=async()=>{setError('');const r=await fetch(`/api/apps/${id}/wallets/${walletId}/support`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'reveal_external_id',reason:'dashboard support'})});const body=await r.json();if(!r.ok)setError(body.error);else setRevealed(body.external_id)};return <div className="space-y-6"><Link href={`/dashboard/apps/${id}/wallets`} className="inline-flex items-center gap-1.5 text-sm text-black/50 hover:text-black"><Icon.ArrowLeft size={14}/>Wallets</Link><header className="rounded-xl border border-line bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h1 className="text-base font-semibold">Wallet support</h1><NetworkBadge network={w.network}/></div><code className="mt-3 block break-all font-mono text-xs text-black/60">{w.address}</code></div><a href={explorer(w.network,w.address)} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 rounded-lg border border-line px-3 py-2 text-xs font-semibold hover:bg-surface">Open explorer <Icon.External size={13}/></a></div><dl className="mt-6 grid gap-5 border-t border-line pt-5 sm:grid-cols-4"><Point label="Created" value={new Date(w.created_at).toLocaleDateString()}/><Point label="Last Cavos interaction" value={new Date(w.updated_at).toLocaleString()}/><Point label="Authorized devices" value={devices.length}/><Point label="Pending recovery" value={pending.length}/></dl></header>
  <section className="rounded-xl border border-line bg-white p-5"><div className="flex items-center justify-between gap-4"><div><h2 className="text-sm font-semibold">External user ID</h2><p className="mt-1 text-xs text-black/45">Masked by default. Reveals are recorded in the audit log.</p></div>{w.can_reveal_external_id&&!revealed&&<button onClick={reveal} className="rounded-lg border border-line px-3 py-2 text-xs font-semibold hover:bg-surface focus-visible:outline-2 focus-visible:outline-brand">Reveal</button>}</div><code className="mt-4 block rounded-lg bg-surface px-3 py-2.5 font-mono text-xs">{revealed??w.external_id_masked??'Not available'}</code>{error&&<p role="alert" className="mt-2 text-xs text-red-700">{error}</p>}</section>
  <section className="rounded-xl border border-line bg-white"><div className="border-b border-line px-5 py-4"><h2 className="text-sm font-semibold">Devices & recovery</h2></div><div className="divide-y divide-line/70">{devices.map((device:any)=><div key={device.id} className="flex items-center gap-3 px-5 py-3.5"><Icon.Device size={17} className="text-black/45"/><div className="flex-1"><p className="text-sm font-medium">{device.device_label||'Authorized device'}</p><p className="text-xs text-black/40">Added {new Date(device.created_at).toLocaleString()}</p></div><span className="text-xs font-semibold text-emerald-700">Authorized</span></div>)}{!devices.length&&<p className="px-5 py-8 text-center text-sm text-black/45">No device metadata registered.</p>}</div></section>
  <section className="space-y-3"><div><h2 className="text-sm font-semibold">Recent Cavos events</h2><p className="mt-1 text-xs text-black/45">No balances or external onchain activity are collected.</p></div><EventTable events={data.events??[]}/></section></div>}
function Point({label,value}:{label:string;value:string|number}){return <div><dt className="text-[10px] font-bold uppercase tracking-widest text-black/40">{label}</dt><dd className="mt-1.5 text-sm font-semibold">{value}</dd></div>}
function explorer(network:string,address:string){if(network.includes('solana'))return `https://explorer.solana.com/address/${address}${network.includes('devnet')?'?cluster=devnet':''}`;if(network.includes('stellar'))return `https://stellar.expert/explorer/${network.includes('test')?'testnet':'public'}/account/${address}`;return `https://${network.includes('sepolia')?'sepolia.':''}starkscan.co/contract/${address}`}
