import { createCipheriv, createDecipheriv, createHash, createHmac, randomBytes } from 'node:crypto'
import { createAdminClient } from '@/lib/supabase/admin'

function encryptionKey() { return createHash('sha256').update(process.env.WEBHOOK_ENCRYPTION_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY || 'local-development-only').digest() }
export function encryptSecret(secret: string) { const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',encryptionKey(),iv),encrypted=Buffer.concat([cipher.update(secret,'utf8'),cipher.final()]);return [iv.toString('base64url'),cipher.getAuthTag().toString('base64url'),encrypted.toString('base64url')].join('.') }
function decryptSecret(value:string){const[iv,tag,data]=value.split('.').map(v=>Buffer.from(v,'base64url'));const decipher=createDecipheriv('aes-256-gcm',encryptionKey(),iv);decipher.setAuthTag(tag);return Buffer.concat([decipher.update(data),decipher.final()]).toString('utf8')}

export async function deliverWebhook(webhook:any,event:any,attempt=1){const admin=createAdminClient();const deliveryId=crypto.randomUUID();const payload=JSON.stringify({version:'2026-07-21',delivery_id:deliveryId,event:{id:event.id,type:event.event_type,status:event.status,severity:event.severity,network:event.network,request_id:event.request_id,tx_reference:event.tx_reference,created_at:event.created_at,metadata:event.metadata}});const secret=decryptSecret(webhook.secret_encrypted);const signature=createHmac('sha256',secret).update(payload).digest('hex');const started=Date.now();let responseStatus:number|null=null,responseBody='',status='failed';try{const response=await fetch(webhook.url,{method:'POST',headers:{'Content-Type':'application/json','X-Cavos-Delivery':deliveryId,'X-Cavos-Signature-256':`sha256=${signature}`},body:payload,signal:AbortSignal.timeout(8000)});responseStatus=response.status;responseBody=(await response.text()).slice(0,500);status=response.ok?'delivered':'failed'}catch(error){responseBody=error instanceof Error?error.message.slice(0,500):'Delivery failed'}await admin.from('webhook_deliveries').insert({id:deliveryId,webhook_id:webhook.id,event_id:event.id,status,attempt,response_status:responseStatus,response_body:responseBody,duration_ms:Date.now()-started,next_attempt_at:status==='failed'&&attempt<5?new Date(Date.now()+[0,15_000,60_000,600_000,3_600_000][attempt]).toISOString():null});await admin.from('webhook_endpoints').update(status==='delivered'?{consecutive_failures:0}:{consecutive_failures:webhook.consecutive_failures+1,is_active:webhook.consecutive_failures+1<10}).eq('id',webhook.id);return {status,responseStatus}}

export async function dispatchEvent(event:any){const admin=createAdminClient();const{data:webhooks}=await admin.from('webhook_endpoints').select('*').eq('environment_id',event.environment_id).eq('is_active',true).contains('event_types',[event.event_type]);for(const webhook of webhooks??[])await deliverWebhook(webhook,event)}
